### ISSUE TITLE
Any plan to support VS 2022

### ISSUE THREAD

**Issue by rizi** [mayerwin/vs-disable-no-source-tab#3]
Hi, any plan to support VS 2022?

Br

**Comment by SylwesterZarebski** [comment]
VS2022 is supported since December 2021, albeit it is not under the same extension name -> https://github.com/mayerwin/vs-disable-no-source-tab/releases .

**Comment by rizi** [comment]
> VS2022 is supported since December 2021, albeit it is not under the same extension name -> https://github.com/mayerwin/vs-disable-no-source-tab/releases .

Thx
